// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace HammondsIBMS_UI_Testing
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ResetDatabase_Test
        /// </summary>
        public void ResetDatabase_Test()
        {
            #region Variable Declarations
            HtmlHyperlink uIAdministrationHyperlink = this.UIIndexWindowsInternetWindow.UIIndexDocument.UIMainMenuCustom.UIAdministrationHyperlink;
            HtmlHyperlink uIResetDatabaseHyperlink = this.UIIndexWindowsInternetWindow.UIIndexDocument.UIMainMenuCustom.UIResetDatabaseHyperlink;
            HtmlDiv uIItemPane1 = this.UIIndexWindowsInternetWindow.UIHttplocalhost1745DatDocument.UIItemPane1;
            #endregion

            // Click 'Administration' link
            Mouse.Click(uIAdministrationHyperlink, new Point(42, 21));

            // Click 'Reset Database' link
            Mouse.Click(uIResetDatabaseHyperlink, new Point(41, 13));

            // The following element is no longer available: IE web control; Process Id [6628], window handle [1770822]

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  pane at (1, 1)
            Mouse.Hover(uIItemPane1, new Point(1, 1));

            // The following element is no longer available: IE web control; Process Id [6628], window handle [1770822]

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }
        
        #region Properties
        public UIIndexWindowsInternetWindow UIIndexWindowsInternetWindow
        {
            get
            {
                if ((this.mUIIndexWindowsInternetWindow == null))
                {
                    this.mUIIndexWindowsInternetWindow = new UIIndexWindowsInternetWindow();
                }
                return this.mUIIndexWindowsInternetWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIIndexWindowsInternetWindow mUIIndexWindowsInternetWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIIndexWindowsInternetWindow : BrowserWindow
    {
        
        public UIIndexWindowsInternetWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Index";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Index");
            this.WindowTitles.Add("http://localhost:1745/Database");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIIndexDocument UIIndexDocument
        {
            get
            {
                if ((this.mUIIndexDocument == null))
                {
                    this.mUIIndexDocument = new UIIndexDocument(this);
                }
                return this.mUIIndexDocument;
            }
        }
        
        public UIHttplocalhost1745DatDocument UIHttplocalhost1745DatDocument
        {
            get
            {
                if ((this.mUIHttplocalhost1745DatDocument == null))
                {
                    this.mUIHttplocalhost1745DatDocument = new UIHttplocalhost1745DatDocument(this);
                }
                return this.mUIHttplocalhost1745DatDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIIndexDocument mUIIndexDocument;
        
        private UIHttplocalhost1745DatDocument mUIHttplocalhost1745DatDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIIndexDocument : HtmlDocument
    {
        
        public UIIndexDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:1745/";
            this.WindowTitles.Add("Index");
            #endregion
        }
        
        #region Properties
        public UIMainMenuCustom UIMainMenuCustom
        {
            get
            {
                if ((this.mUIMainMenuCustom == null))
                {
                    this.mUIMainMenuCustom = new UIMainMenuCustom(this);
                }
                return this.mUIMainMenuCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIMainMenuCustom mUIMainMenuCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMainMenuCustom : HtmlCustom
    {
        
        public UIMainMenuCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "mainMenu";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "nav";
            this.FilterProperties["ControlDefinition"] = "class=\"nav\" id=\"mainMenu\"";
            this.FilterProperties["TagInstance"] = "2";
            this.WindowTitles.Add("Index");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAdministrationHyperlink
        {
            get
            {
                if ((this.mUIAdministrationHyperlink == null))
                {
                    this.mUIAdministrationHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAdministrationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAdministrationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAdministrationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAdministrationHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Administration ";
                    this.mUIAdministrationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIAdministrationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAdministrationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:1745/#";
                    this.mUIAdministrationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "dropdown-toggle";
                    this.mUIAdministrationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"dropdown-toggle\" href=\"#\" data-to";
                    this.mUIAdministrationHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIAdministrationHyperlink.WindowTitles.Add("Index");
                    #endregion
                }
                return this.mUIAdministrationHyperlink;
            }
        }
        
        public HtmlHyperlink UIResetDatabaseHyperlink
        {
            get
            {
                if ((this.mUIResetDatabaseHyperlink == null))
                {
                    this.mUIResetDatabaseHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIResetDatabaseHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIResetDatabaseHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIResetDatabaseHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIResetDatabaseHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Reset Database ";
                    this.mUIResetDatabaseHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Database";
                    this.mUIResetDatabaseHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIResetDatabaseHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:1745/Database";
                    this.mUIResetDatabaseHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIResetDatabaseHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Database\" data-parent=\"0\"";
                    this.mUIResetDatabaseHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIResetDatabaseHyperlink.WindowTitles.Add("Index");
                    #endregion
                }
                return this.mUIResetDatabaseHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAdministrationHyperlink;
        
        private HtmlHyperlink mUIResetDatabaseHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIHttplocalhost1745DatDocument : HtmlDocument
    {
        
        public UIHttplocalhost1745DatDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Database";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:1745/Database";
            this.WindowTitles.Add("http://localhost:1745/Database");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "t-overlay";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"t-overlay\" style=\"display: block; z-index: 10006; opacity: 0.0454626;\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
                    this.mUIItemPane.WindowTitles.Add("http://localhost:1745/Database");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlDiv UIItemPane1
        {
            get
            {
                if ((this.mUIItemPane1 == null))
                {
                    this.mUIItemPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "t-overlay";
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"t-overlay\" style=\"display: block; z-index: 10006; opacity: 0.0598985;\"";
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
                    this.mUIItemPane1.WindowTitles.Add("http://localhost:1745/Database");
                    #endregion
                }
                return this.mUIItemPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIItemPane;
        
        private HtmlDiv mUIItemPane1;
        #endregion
    }
}
